### ISSUE TITLE
make sparql query for wiki wikipathways

### ISSUE THREAD

**Issue by MartijnAB** [MartijnAB/from-toxicological-data-to-toxicological-information#21]

**Comment by mkutmon** [comment]
RDF data itself: http://data.wikipathways.org/current/rdf/

**Comment by mkutmon** [comment]
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?label ?wikidata WHERE {
  ?metabolite a wp:Metabolite .
  ?metabolite rdfs:label ?label .
  ?metabolite dcterms:isPartOf ?pathway .
  ?pathway a wp:Pathway .
  ?pathway dcterms:identifier "WP1604"^^xsd:string .
  ?metabolite wp:bdbWikidata ?wikidata .
}

**Comment by mkutmon** [comment]
Prefixes: 
```
PREFIX gpml:    <http://vocabularies.wikipathways.org/gpml#>
PREFIX wp:      <http://vocabularies.wikipathways.org/wp#>
PREFIX cur:     <http://vocabularies.wikipathways.org/wp#Curation:>
PREFIX wprdf:   <http://rdf.wikipathways.org/>
PREFIX biopax:  <http://www.biopax.org/release/biopax-level3.owl#> 
PREFIX cas:     <http://identifiers.org/cas/>
PREFIX dc:      <http://purl.org/dc/elements/1.1/> 
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/> 
PREFIX ncbigene:<http://identifiers.org/ncbigene/>
PREFIX pubmed:  <http://www.ncbi.nlm.nih.gov/pubmed/> 
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#> 
```

**Comment by MartijnAB** [comment]
@DeniseSl22 

de labels (zo als deze ""Morphine-6-glucuronide"^^<http://www.w3.org/2001/XMLSchema#string>") zijn toch de officiële namen van de stoven zo als ze in wikipathways staan.

En deze manier is toch ook de officiële en uniek manier hoe een chemische naam gesreven hoor te worden? en zo je hoe heet die benamis metode in het enels? zo dat ik dat als vaiablen naam kan gebruiken in de class "ChemicalCompound"

**Comment by MartijnAB** [comment]
> @DeniseSl22
> 
> de labels (zo als deze ""Morphine-6-glucuronide"^^http://www.w3.org/2001/XMLSchema#string") zijn toch de officiële namen van de stoven zo als ze in wikipathways staan.
> 
> En deze manier is toch ook de officiële en uniek manier hoe een chemische naam gesreven hoor te worden? en zo je hoe heet die benamis metode in het enels? zo dat ik dat als vaiablen naam kan gebruiken in de class "ChemicalCompound"

nee het is een door de gebruiker in gevoerde naam
