### ISSUE TITLE
find out how to go from a chemical id to smiles

### ISSUE THREAD

**Issue by MartijnAB** [MartijnAB/from-toxicological-data-to-toxicological-information#23]

**Comment by egonw** [comment]
@MartijnAB, the link is http://orn-chemidconvert-chemidconvert.prod.openrisknet.org/v1/ui/ (from the home.prod webpage), but this server seems to have issues right now (reported) and I get a HTTP 504 :(

**Comment by MartijnAB** [comment]
dank u. Maar voor nu is het geen probleem om dat we het via wikidata gaan doen

**Comment by MartijnAB** [comment]
Is niet meer nodig want we gaan het nu don via wikidata en misschien wel zonder smiles.
